/-
  GENERATED by scripts/gen_data.py from the frozen certificate inputs. Do not edit by hand.
  Source (SHA-256):
    barriers.json  9f89d11ed4cff2ba66edd9b5490af039d4ea89f93505221cca1a9b27b8b269a6
-/
import DBN.Certificate

namespace DBN.Data
/-- Source boxes: 0 = box A (V > 289/100), 1..9 = ALL catalog, 10..25 = FORWARD catalog. Fields: id, floor L, h_lo, h_hi, t_lo, t_hi. -/
def catalog : Array SourceCert := #[
  ⟨0, mkRat 289 100, mkRat 6499 10000, mkRat 651 1000, mkRat 3 50, mkRat 601 10000⟩,
  ⟨1, mkRat 721709 250000, mkRat 6469 10000, mkRat 6501 10000, mkRat 601 10000, mkRat 303 5000⟩,
  ⟨2, mkRat 2884841 1000000, mkRat 161 250, mkRat 809 1250, mkRat 303 5000, mkRat 611 10000⟩,
  ⟨3, mkRat 144133 50000, mkRat 641 1000, mkRat 1611 2500, mkRat 611 10000, mkRat 77 1250⟩,
  ⟨4, mkRat 2880433 1000000, mkRat 319 500, mkRat 1283 2000, mkRat 77 1250, mkRat 621 10000⟩,
  ⟨5, mkRat 2878157 1000000, mkRat 127 200, mkRat 3193 5000, mkRat 621 10000, mkRat 313 5000⟩,
  ⟨6, mkRat 2875831 1000000, mkRat 79 125, mkRat 6357 10000, mkRat 313 5000, mkRat 631 10000⟩,
  ⟨7, mkRat 1436727 500000, mkRat 629 1000, mkRat 791 1250, mkRat 631 10000, mkRat 159 2500⟩,
  ⟨8, mkRat 179439 62500, mkRat 313 500, mkRat 3149 5000, mkRat 159 2500, mkRat 641 10000⟩,
  ⟨9, mkRat 2868539 1000000, mkRat 623 1000, mkRat 6269 10000, mkRat 641 10000, mkRat 323 5000⟩,
  ⟨10, mkRat 573541 200000, mkRat 12421 20000, mkRat 6241 10000, mkRat 323 5000, mkRat 651 10000⟩,
  ⟨11, mkRat 716347 250000, mkRat 3091 5000, mkRat 497 800, mkRat 651 10000, mkRat 41 625⟩,
  ⟨12, mkRat 1431511 500000, mkRat 12307 20000, mkRat 773 1250, mkRat 41 625, mkRat 661 10000⟩,
  ⟨13, mkRat 572121 200000, mkRat 49 80, mkRat 12311 20000, mkRat 661 10000, mkRat 333 5000⟩,
  ⟨14, mkRat 2858137 1000000, mkRat 12193 20000, mkRat 6127 10000, mkRat 333 5000, mkRat 671 10000⟩,
  ⟨15, mkRat 44619 15625, mkRat 1517 2500, mkRat 12197 20000, mkRat 671 10000, mkRat 169 2500⟩,
  ⟨16, mkRat 35663 12500, mkRat 12079 20000, mkRat 607 1000, mkRat 169 2500, mkRat 681 10000⟩,
  ⟨17, mkRat 2850409 1000000, mkRat 6011 10000, mkRat 12083 20000, mkRat 681 10000, mkRat 343 5000⟩,
  ⟨18, mkRat 2847721 1000000, mkRat 2393 4000, mkRat 6013 10000, mkRat 343 5000, mkRat 691 10000⟩,
  ⟨19, mkRat 2844973 1000000, mkRat 2977 5000, mkRat 11969 20000, mkRat 691 10000, mkRat 87 1250⟩,
  ⟨20, mkRat 568433 200000, mkRat 11851 20000, mkRat 1489 2500, mkRat 87 1250, mkRat 701 10000⟩,
  ⟨21, mkRat 567859 200000, mkRat 5897 10000, mkRat 2371 4000, mkRat 701 10000, mkRat 353 5000⟩,
  ⟨22, mkRat 70909 25000, mkRat 11737 20000, mkRat 5899 10000, mkRat 353 5000, mkRat 711 10000⟩,
  ⟨23, mkRat 35417 12500, mkRat 73 125, mkRat 11741 20000, mkRat 711 10000, mkRat 179 2500⟩,
  ⟨24, mkRat 2830293 1000000, mkRat 11623 20000, mkRat 2921 5000, mkRat 179 2500, mkRat 721 10000⟩,
  ⟨25, mkRat 565431 200000, mkRat 5783 10000, mkRat 11627 20000, mkRat 721 10000, mkRat 363 5000⟩
]

end DBN.Data
