/- GENERATED by scripts/gen_data.py. Concatenation (as a List, linear for the kernel) of the 7849 rows in 16 chunks. -/
import DBN.Data.fullCRows0
import DBN.Data.fullCRows1
import DBN.Data.fullCRows2
import DBN.Data.fullCRows3
import DBN.Data.fullCRows4
import DBN.Data.fullCRows5
import DBN.Data.fullCRows6
import DBN.Data.fullCRows7
import DBN.Data.fullCRows8
import DBN.Data.fullCRows9
import DBN.Data.fullCRows10
import DBN.Data.fullCRows11
import DBN.Data.fullCRows12
import DBN.Data.fullCRows13
import DBN.Data.fullCRows14
import DBN.Data.fullCRows15

namespace DBN.Data

def fullCRows : List Row := fullCRows0.toList ++ fullCRows1.toList ++ fullCRows2.toList ++ fullCRows3.toList ++ fullCRows4.toList ++ fullCRows5.toList ++ fullCRows6.toList ++ fullCRows7.toList ++ fullCRows8.toList ++ fullCRows9.toList ++ fullCRows10.toList ++ fullCRows11.toList ++ fullCRows12.toList ++ fullCRows13.toList ++ fullCRows14.toList ++ fullCRows15.toList

end DBN.Data
