/- GENERATED by scripts/gen_data.py. Concatenation (as a List, linear for the kernel) of the 4817 rows in 10 chunks. -/
import DBN.Data.mainRows0
import DBN.Data.mainRows1
import DBN.Data.mainRows2
import DBN.Data.mainRows3
import DBN.Data.mainRows4
import DBN.Data.mainRows5
import DBN.Data.mainRows6
import DBN.Data.mainRows7
import DBN.Data.mainRows8
import DBN.Data.mainRows9

namespace DBN.Data

def mainRows : List Row := mainRows0.toList ++ mainRows1.toList ++ mainRows2.toList ++ mainRows3.toList ++ mainRows4.toList ++ mainRows5.toList ++ mainRows6.toList ++ mainRows7.toList ++ mainRows8.toList ++ mainRows9.toList

end DBN.Data
