#!/usr/bin/env python3
"""Generate Lean Row/Cert data from the standalone normalized certificate.

--check compares every generated byte without writing, including provenance
comments, declarations, imports, field order, rational literals, and chunk order.

The mathematical acceptance checks live in the certificate checkers and Lean;
this generator only translates exact data and resolves catalog references.
"""

import argparse
from fractions import Fraction
import hashlib
import json
from pathlib import Path
import sys

LEAN = Path(__file__).resolve().parent.parent
INPUT = LEAN.parent / "certificate" / "data" / "barriers.json"
OUT = LEAN / "DBN" / "Data"


def literal(value):
    value = Fraction(value)
    return f"mkRat {value.numerator} {value.denominator}"


def source_literal(source):
    values = [str(source["id"])]
    values += [literal(source[key]) for key in ("L", "hlo", "hhi", "btl", "btr")]
    return "⟨" + ", ".join(values) + "⟩"


def field_literal(field):
    if not isinstance(field["signed"], bool):
        raise ValueError("field.signed must be a JSON boolean")
    values = ["true" if field["signed"] else "false"]
    values += [literal(field[key]) for key in ("p", "s", "c", "qM")]
    values += [str(field["mIdx"]), literal(field["otl"]), literal(field["otr"]), str(field["oIdx"])]
    return "⟨" + ", ".join(values) + "⟩"


def row_literal(row, certificate):
    values = [literal(row[key]) for key in ("tl", "tr", "qL", "qR")]
    return "⟨" + ", ".join(values + [certificate]) + "⟩"


def generate(raw):
    data = json.loads(raw)
    if data["schema_version"] != 1:
        raise ValueError("unsupported certificate schema")
    sources, reference, main, wall = (data[k] for k in ("sources", "reference", "main", "wall"))
    if [s["id"] for s in sources] != list(range(26)):
        raise ValueError("expected source ids 0..25 in order")
    if (len(main), len(reference), len(wall)) != (4817, 7849, 1620):
        raise ValueError("unexpected certificate dimensions")
    fields = [field_literal(row["field"]) for row in reference]
    main_literals = []
    for row in main:
        if ("source" in row) == ("field" in row):
            raise ValueError("each main row must carry exactly one certificate reference")
        if "source" in row:
            index = row["source"]
            if type(index) is not int or not 0 <= index < len(sources):
                raise ValueError("invalid source reference")
            certificate = ".source " + source_literal(sources[index])
        else:
            index = row["field"]
            if type(index) is not int or not 0 <= index < len(reference):
                raise ValueError("invalid field reference")
            certificate = ".field " + fields[index]
        main_literals.append(row_literal(row, certificate))
    reference_literals = [
        row_literal(row, ".field " + field) for row, field in zip(reference, fields)
    ]
    header = (
        "/-\n  GENERATED by scripts/gen_data.py from the frozen certificate inputs. Do not edit by hand.\n"
        "  Source (SHA-256):\n"
        f"    barriers.json  {hashlib.sha256(raw).hexdigest()}\n"
        "-/\nimport DBN.Certificate\n\nnamespace DBN.Data\n"
    )
    outputs = {}

    def chunks(prefix, items, size=500, lean_type="Row"):
        names = []
        for start in range(0, len(items), size):
            name = f"{prefix}{start // size}"
            names.append(name)
            body = ",\n  ".join(items[start : start + size])
            outputs[f"{name}.lean"] = (
                header
                + f"set_option maxRecDepth 100000 in\ndef {name} : Array {lean_type} := #[\n  "
                + body
                + "\n]\n\nend DBN.Data\n"
            )
        imports = "\n".join(f"import DBN.Data.{name}" for name in names)
        concat = " ++ ".join(f"{name}.toList" for name in names)
        outputs[f"{prefix}.lean"] = (
            f"/- GENERATED by scripts/gen_data.py. Concatenation (as a List, linear for the kernel) of the {len(items)} rows in {len(names)} chunks. -/\n"
            f"{imports}\n\nnamespace DBN.Data\n\ndef {prefix} : List {lean_type} := {concat}\n\nend DBN.Data\n"
        )

    chunks("mainRows", main_literals)
    chunks("fullCRows", reference_literals)
    segments = [
        "⟨" + ", ".join(literal(row[k]) for k in ("tl", "tr", "qL", "qR")) + "⟩" for row in wall
    ]
    outputs["Wall.lean"] = (
        header
        + "set_option maxRecDepth 100000 in\n/-- The 1620 affine cells of the M3a trace q_M (field wall). -/\ndef wall : Array Seg := #[\n  "
        + ",\n  ".join(segments)
        + "\n]\n\nend DBN.Data\n"
    )
    outputs["Catalog.lean"] = (
        header
        + "/-- Source boxes: 0 = box A (V > 289/100), 1..9 = ALL catalog, 10..25 = FORWARD catalog. Fields: id, floor L, h_lo, h_hi, t_lo, t_hi. -/\ndef catalog : Array SourceCert := #[\n  "
        + ",\n  ".join(map(source_literal, sources))
        + "\n]\n\nend DBN.Data\n"
    )
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument(
        "--check", action="store_true", help="compare all generated bytes without writing"
    )
    args = parser.parse_args()
    outputs = generate(INPUT.read_bytes())
    if args.check:
        differences = [
            name
            for name, expected in outputs.items()
            if not (OUT / name).is_file() or (OUT / name).read_text() != expected
        ]
        if differences:
            print("generated Lean data differs: " + ", ".join(differences), file=sys.stderr)
            return 1
        print(f"PASS: {len(outputs)} generated Lean complete files match exactly")
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in outputs.items():
        (OUT / name).write_text(text)
    print("wrote 4817 main rows, 7849 fullC rows, 1620 wall cells, 26 catalog boxes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
